### ISSUE TITLE
Request of the replace diagram

### ISSUE THREAD

**Issue by AlexHTP** [ManCloud/S-MIX-replacement#1]
Hello, 
I know the project have some issues as you say in the forum but with my null knowledge of german (i'm mexican) and the google translator i'm incapable of understand more than a few lines of those you wrote. I want try to fix my snes with your diagram and so i make you the kind request of it and if you can, i want to ask you for an explanation in english of the issue that made you desist from continue the project. I hope this isn't very intrusive or unrespectfull i only want to fix my snes.

**Comment by ManCloud** [comment]
Hi ^^ 

The reason why I stopped working on this was simply that the console which needed it died completely because I forgot to discharge the capacitor at the psu.

There is one guy in the forum which already built the board based on the information here in github and except one thing (he says he has a little buzzing in the audio) it works as expected.

What diagramm exactly do you want me to put into english?

I'll do whatever I can to support you best .

Cya
ManCloud
